### ISSUE TITLE
Can we have a changelog 

### ISSUE THREAD

**Issue by eoinfogarty** [satorufujiwara/exoplayer-textureview#17]
It would be useful if you could create a changelog for when you version up.
This is so we can see what changes have been made and if it will affect our projects.

For example Picasso provides a changelog to keep us up to date
https://github.com/square/picasso/blob/master/CHANGELOG.md

**Comment by satorufujiwara** [comment]
Ok. I'll add CHANGELOG.md when I version up next.

**Comment by satorufujiwara** [comment]
Fixed with #18

**Comment by eoinfogarty** [comment]
Thank you!
